version: "3.3"
services:
  front-end: 
    image: ziliadmin
    volumes:
      - /opt/zili-admin:/usr/local/apache2/htdocs/app
    ports:
      - '80:80'
    environment:
      - MY_SERVER_NAME=zili.admin.com