version: "3.3"
services:
  nginx: 
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      gau_net:
        ipv4_address: 172.16.238.9
  tmadmin: 
    image: web
    volumes:
      - /opt/sources/tmadmin:/usr/local/apache2/htdocs/app
    ports:
      - '10:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.10
  apis: 
    image: web
    volumes:
      - /opt/sources/zend:/usr/local/apache2/htdocs/app
    ports:
      - '11:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.11
  redisearch: 
    image: redislabs/redisearch:latest
    ports:
      - '6379:6379'
    networks:
      gau_net:
        ipv4_address: 172.16.238.12
  mysql: 
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - /var/opt/mysql:/var/lib/mysql
    networks:
      gau_net:
        ipv4_address: 172.16.238.13
  awsgateway: 
    image: web
    volumes:
      - /var/opt/sources/admin-dashboard:/usr/local/apache2/htdocs/app
    ports:
      - '14:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.14

################################################################################
# NETWORK
################################################################################
networks:
  gau_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
   