version: "3.3"
services:
  front-end: 
    image: web
    volumes:
      - /home/admin-tools:/usr/local/apache2/htdocs/app
    ports:
      - '10:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.10


################################################################################
# NETWORK
################################################################################
networks:
  gau_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
   