version: "3.3"
services:
  nginx: 
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      gau_net:
        ipv4_address: 172.16.238.9
  tmadmin: 
    image: web
    volumes:
      - /opt/sources/tmadmin:/usr/local/apache2/htdocs/app
    ports:
      - '10:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.10
  redisearch: 
    image: redislabs/redisearch:latest
    ports:
      - '6379:6379'
    networks:
      gau_net:
        ipv4_address: 172.16.238.11
  sorl-search: 
    image: web
    volumes:
      - /opt/mss/BSS_Batch_Import_Solr:/usr/local/apache2/htdocs/app
    ports:
      - '12:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.12


################################################################################
# NETWORK
################################################################################
networks:
  gau_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
   