version: "3.3"
services:
  front-end: 
    image: web
    volumes:
      - /opt/sources/mss/BSS_HK_Front:/usr/local/apache2/htdocs/app
    ports:
      - '80:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.10
    extra_hosts:
      - "search-service.com:192.168.88.221"
      - "shop-service.com:172.16.238.14"
      - "customer-service.com:172.16.238.16"
  common: 
    image: web
    volumes:
      - /opt/sources/mss/BSS_Common_Services:/usr/local/apache2/htdocs/app
    networks:
      gau_net:
        ipv4_address: 172.16.238.11
    extra_hosts:
      - "search-service.com:192.168.88.221"
      - "shop-service.com:172.16.238.14"
      - "customer-service.com:172.16.238.16"
    ports:
      - '11:80'
  media: 
    image: web
    volumes:
      - /opt/sources/mss/BSS_Media_Services:/usr/local/apache2/htdocs/app
    ports:
      - '12:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.12
    ports:
      - '12:80'
    extra_hosts:
      - "search-service.com:192.168.88.221"
      - "shop-service.com:172.16.238.14"
      - "customer-service.com:172.16.238.16"
  post: 
    image: web
    volumes:
      - /opt/sources/mss/BSS_Post_Services:/usr/local/apache2/htdocs/app
    networks:
      gau_net:
        ipv4_address: 172.16.238.13
    ports:
      - '13:80'
    extra_hosts:
      - "search-service.com:192.168.88.221"
      - "shop-service.com:172.16.238.14"
      - "customer-service.com:172.16.238.16"
  shop: 
    image: web
    volumes:
      - /opt/sources/mss/BSS_Shop_Services:/usr/local/apache2/htdocs/app
    ports:
      - '14:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.14
    extra_hosts:
      - "search-service.com:192.168.88.221"
      - "shop-service.com:172.16.238.14"
      - "customer-service.com:172.16.238.16"
  thumbor: 
    image: apsl/thumbor
    ports:
      - '8000:8000'
    ports:
      - '15:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.15
  customer: 
    image: web
    volumes:
      - /opt/sources/mss/BSS_Customer_Services:/usr/local/apache2/htdocs/app
    ports:
      - '16:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.16
    extra_hosts:
      - "search-service.com:192.168.88.221"
      - "shop-service.com:172.16.238.14"
      - "customer-service.com:172.16.238.16"

################################################################################
# NETWORK
################################################################################
networks:
  gau_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
   