version: "3.3"
services:
  front-end: 
    image: vunguyenvu35/laravel-on-k8s:v3
    volumes:
      - /opt/sources/mss/BSS_HK_Front:/usr/local/apache2/htdocs/app
    ports:
      - '80:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.10
    extra_hosts:
      - "search-service.com:192.168.88.230"
      - "shop-service.com:172.16.238.14"
      - "customer-service.com:172.16.238.16"

################################################################################
# NETWORK
################################################################################
networks:
  gau_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
   